---

- include: zabbix_agent_centos.yml
  when: ansible_distribution == "CentOS"

#- include: zabbix_agent_ubuntu.yml
#  when: ansible_distribution == "Ubuntu"

- include: zabbix_scripts.yml
  when: zabbix_agent_custom_scripts_deploy

- name: SSH Tunnel management for zabbix
  include: mon_user.yml
  when: zabbix_agent_tunnel

