# zabbix_version
zabbix_agent_major                : "2"
zabbix_agent_minor                : "2"
zabbix_agent_release              : "4"

# passive check
zabbix_agent_Server               : "172.20.0.32"  ## List of comma delimited IP addresses (or hostnames) of Zabbix servers.

# active check
zabbix_agent_ServerActive         : "172.20.0.32"

# host metadata
zabbix_agent_HostMetadata         : "Linux  test  45XB32HbaF+aQRvG/IkSjTMrcGfYVtBuLSeSzi7G"
